
[entryPoints]
  [entryPoints.https]
  address = ":443"
  
  [entryPoints.http]
  address = ":80"

  [entryPoints.traefik]
  address = ":8080"


################################################################
# API and dashboard configuration
################################################################
[api]
#entryPoint = "traefik"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "docker.local"
watch = true
