version: '3'
services:
  xc5hub:
    image: library/nginx
    container_name: test8196
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: test8196.${domain}, www.test8196.${domain}
      LETSENCRYPT_HOST: test8196.${domain}, www.test8196.${domain}
      LETSENCRYPT_EMAIL: k-Laus@gmx.net
    expose:
      - "80"
      - "443"
networks:
   default:
     external:
       name: nginx-proxy
