version: '3.5'

services:
  traefik:
    image: traefik:1.7.3
    container_name: traefik
    hostname: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    expose:
      - 8080
    networks:
      - outline
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/traefik/acme.json:/acme.json
    labels:
      traefik.backend: "traefik"
      traefik.enable: true
      traefik.frontent.rule: "Host:traefik.docker.local"
      traefik.port: "8080"
      traefik.docker.network: "outline"
networks:
  outline:
    name: outline 
  default:
    external: true
    internal: true
    name: host
