version: '3'
services:
  xc5hub:
    image: library/nginx
    container_name: xc5hub
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: xc5hub.de, www.xc5hub.de
      LETSENCRYPT_HOST: xc5hub.de, www.xc5hub.de
      LETSENCRYPT_EMAIL: k-Laus@gmx.net
    expose:
      - "80"
      - "443"
    volumes:
      - /srv/de.xc5hub/:/usr/share/nginx/html:ro
  xc5hub-db:
    image: mariadb
    container_name: xc5hub-db
    volumes:
      - /srv/de.xc5hub.blog/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress!23
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress!23
    restart: unless-stopped
  xc5hub-wp:
    depends_on:
      - xc5hub-db
    image: wordpress
    container_name: xc5hub-wp
    environment:
      - WORDPRESS_DB_HOST=xc5hub-db:3306
      - WORDPRESS_DB_PASSWORD=wordpress!23
      - VIRTUAL_HOST=blog.xc5hub.de
      - LETSENCRYPT_HOST=blog.xc5hub.de
      - LETSENCRYPT_EMAIL=k-Laus@gmx.net
    restart: unless-stopped
networks:
   default:
     external:
       name: nginx-proxy
