# an example https://github.com/jacobalberty/unifi-docker/blob/master/docker-compose.yml
version: '3.4'
services:
  mongo:
    image: mongo:3.4
    container_name: unifi-db
    restart: unless-stopped
    volumes:
      - /srv/unifi-db:/data/db
  controller:
    image: jacobalberty/unifi
    container_name: unifi 
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=unifi.khome.2ng.de
      - VIRTUAL_PORT=8443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=unifi.khome.2ng.de
      - LETSENCRYPT_EMAIL=k-Laus@gmx.net
      - RUNAS_UID0=false
      - UNIFI_UID=1000
      - UNIFI_GID=1000
      - DB_URI=mongodb://unifi-db/unifi
      - STATDB_URI=mongodb://unifi-db/unifi_stat
      - DB_NAME=unifi
    volumes:
      - /srv/unifi:/unifi
    #expose:
    #  - "8443"
    ports:
     #- "8443:8443"
     - "3478:3478/udp"
     #- "10001:10001/udp"
     - "8080:8080"
networks:
   default:
     external:
       name: nginx-proxy
