# an example https://github.com/jacobalberty/unifi-docker/blob/master/docker-compose.yml
version: '3.4'
services:
  controller:
    image: jacobalberty/unifi
    container_name: unifi 
    environment:
      - VIRTUAL_HOST=unifi.khome.2ng.de
      - LETSENCRYPT_HOST=unifi.khome.2ng.de
      - LETSENCRYPT_EMAIL=k-Laus@gmx.net
      - RUNAS_UID0=false
      - UNIFI_UID=1000
      - UNIFI_GID=1000
    volumes:
      - /srv/unifi:/unifi
    restart: unless-stopped
    expose:
      - "8880"
    ports:
     - "8443:8443"
     - "3478:3478/udp"
     - "10001:10001/udp"
     - "8080:8080"
networks:
   default:
     external:
       name: nginx-proxy
